INSERT INTO `socios` (`estado_id`, `nombre`, `apellido`, `email`) VALUES
(1, 'Carlos', 'Gómez', 'carlos.gomez@email.com'),
(1, 'Lucía', 'Pérez', 'lucia.perez@email.com'),
(1, 'Mateo', 'Rodríguez', 'mateo.rodriguez@email.com'),
(1, 'Sofía', 'Martínez', 'sofia.martinez@email.com'),
(1, 'Alejandro', 'López', 'alejandro.lopez@email.com'),
(1, 'Valentina', 'González', 'valentina.gonzalez@email.com'),
(1, 'Joaquín', 'Díaz', 'joaquin.diaz@email.com'),
(1, 'Martina', 'Fernández', 'martina.fernandez@email.com'),
(1, 'Lucas', 'López', 'lucas.lopez@email.com'),
(1, 'Camila', 'Romero', 'camila.romero@email.com'),
(1, 'Facundo', 'Sosa', 'facundo.sosa@email.com'),
(1, 'Julieta', 'Torres', 'julieta.torres@email.com'),
(1, 'Nicolás', 'Ruiz', 'nicolas.ruiz@email.com'),
(1, 'Florencia', 'Álvarez', 'florencia.alvarez@email.com'),
(1, 'Agustín', 'Moreno', 'agustin.moreno@email.com'),
(1, 'Micaela', 'Jiménez', 'micaela.jimenez@email.com'),
(1, 'Tomás', 'Castillo', 'tomas.castillo@email.com'),
(1, 'Victoria', 'Acosta', 'victoria.acosta@email.com'),
(1, 'Ignacio', 'Flores', 'ignacio.flores@email.com'),
(1, 'Antonella', 'Medina', 'antonella.medina@email.com'),
(1, 'Franco', 'Suárez', 'franco.suarez@email.com'),
(1, 'Catalina', 'García', 'catalina.garcia@email.com'),
(1, 'Thiago', 'Castro', 'thiago.castro@email.com'),
(1, 'Milagros', 'Ortiz', 'milagros.ortiz@email.com'),
(1, 'Bautista', 'Rubio', 'bautista.rubio@email.com'),
(1, 'Renata', 'Silva', 'renata.silva@email.com'),
(1, 'Dante', 'Peralta', 'peralta.dante@email.com'),
(1, 'Clara', 'Benítez', 'clara.benitez@email.com'),
(1, 'Santino', 'Vargas', 'santino.vargas@email.com'),
(1, 'Emilia', 'Mendoza', 'emilia.mendoza@email.com'),
(2, 'Bruno', 'Iglesias', 'bruno.iglesias@email.com'),
(2, 'Abigail', 'Ríos', 'abigail.rios@email.com'),
(2, 'Maximiliano', 'Bravo', 'maximiliano.bravo@email.com'),
(2, 'Jazmín', 'Cabrera', 'jazmin.cabrera@email.com'),
(2, 'Gonzalo', 'Paz', 'gonzalo.paz@email.com');


INSERT INTO `canchas` (`nombre`, `deporte_id`, `precio_hora`, `techada`, `activa`) VALUES
('Cancha Fútbol 5 - Sintético 1', 1, 4500, 1, 1),
('Cancha Fútbol 5 - Sintético 2', 1, 5000, 0, 1),
('Cancha Fútbol 7 - Techada', 1, 7500, 1, 1),
('Cancha Fútbol 11 - Principal', 1, 10000, 0, 1),
('Cancha Fútbol 5 - Los Pinos', 1, 3800, 1, 1),

('Cancha Básquet Cubierta A', 2, 6000, 1, 1),
('Cancha Básquet Cubierta B', 2, 6500, 1, 1),
('Cancha Básquet Abierta 1', 2, 3500, 0, 1),
('Cancha Básquet Abierta 2', 2, 4000, 0, 1),
('Cancha Básquet Profesional', 2, 9000, 1, 1),

('Cancha Voley Sintética 1', 3, 3200, 0, 1),
('Cancha Voley Sintética 2', 3, 3500, 0, 1),
('Cancha Voley Techada 1', 3, 5500, 1, 1),
('Cancha Voley Techada 2', 3, 6000, 1, 1),
('Cancha Voley Arena (Beach)', 3, 4800, 0, 1);
